### ISSUE TITLE
Qconversion from 2Theta Chi plots

### ISSUE THREAD

**Issue by ravipurohit1991** [dkriegner/xrayutilities#125]
Hello,

I have a multi-detector configuration (hence a final output in 2theta and Chi (result of 2D integration) for images from area detector treated with PyFAI). I would like to use this information (2theta and Chi, instead of the Image pixels information) to map the reciprocal space.
Is there a way to do it with XrayUtilities ?

Thank you for the help.
Ravi.

**Comment by dkriegner** [comment]
In principle x-rayutilities is exactly the right tool for conversion from angular to reciprocal space coordinates. 
You just have to understand if any of the built in goniometer geometries decribes your case, or if you need to define your own [QConversion](https://xrayutilities.sourceforge.io/xrayutilities.html?highlight=qconversion#xrayutilities.experiment.QConversion). 

I am afraid the information you specify is totally insufficient (and I have no experience with PyFAI) so that I can not judge this and you will have to find out yourself. I would start looking at the [FourC](https://xrayutilities.sourceforge.io/_modules/xrayutilities/experiment.html#FourC).
