### ISSUE TITLE
Kappa diffractometer

### ISSUE THREAD

**Issue by brussel13** [dkriegner/xrayutilities#132]
I wonder if any thought has been put into implementation of Kappa geometry diffractometers.  One could imagine specifying an axis with something like "30x+60y+" to represent that the axis lies in the xy plane at 30 degrees to positive x and 60 to positive y?
It's possible there is a way to do this already and I have just missed it.

https://journals.iucr.org/j/issues/1999/05/00/gl0599/gl0599.pdf

**Comment by dkriegner** [comment]
yes there is a way to do this already. The problem is the bad documentation
of this and many other features.

Please look at
https://github.com/dkriegner/xrayutilities/blob/main/examples/xrayutilities_experiment_kappa.py
and see if this explains it sufficiently.

**Comment by dkriegner** [comment]
@brussel13 if the previous comment answers your question, this issue could be closed?

**Comment by brussel13** [comment]
Dominik,

Yes, I did find the kappa support.  Thank you.
Is there any consideration of a more general axis definition?
Please feel free to close the this.

Ross

________________________________

**Comment by dkriegner** [comment]
Hi, sorry for late reply.

> Is there any consideration of a more general axis definition?

I am not sure if I understand the question. As I see it, one can with the current code define a completely general axis direction. It might need that one adds some fake axis to provide the rotation of the axis but its possible.

I also must omit that non-orthogonal axis is not something I saw often. Since the kappa axis which seems to be the only frequent implemtation is somewhat handles rather easily I see no need for code changes at the moment. 

If someone indeed has a goniometer which has multiple weirdly oriented rotation axis one might want to change things a bit. But using some fake axis to provide the tilt of the rotation axis even this can be implemented with the current code (but I agree this is not elegant in this case).

cheers
Dominik
