### ISSUE TITLE
1.7.4 warning during the Debian build process (test)

### ISSUE THREAD

**Issue by picca** [dkriegner/xrayutilities#143]
Just for info I put here the warning observed durong the packaging  of the 1.7.4 version on Debian.

cheers

=============================== warnings summary ===============================
tests/test_examples.py:70
  /<<PKGBUILDDIR>>/.pybuild/cpython3_3.10_xrayutilities/build/tests/test_examples.py:70: PytestCollectionWarning: cannot collect test class 'TestExampleScriptsMeta' because it has a __init__ constructor (from: .pybuild/cpython3_3.10_xrayutilities/build/tests/test_examples.py)
    class TestExampleScriptsMeta(type):

../../../../../../usr/lib/python3/dist-packages/past/builtins/misc.py:45
  /usr/lib/python3/dist-packages/past/builtins/misc.py:45: DeprecationWarning: the imp module is deprecated in favour of importlib and slated for removal in Python 3.12; see the module's documentation for alternative uses
    from imp import reload

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html

**Comment by dkriegner** [comment]
thanks for reporting this.

I think the first one is somehow unavoidable since we do not hardcode the tests for running the examples. I see it also on the [azure pipeline tests](https://dev.azure.com/dominikkriegner/xrayutilities/_build/results?buildId=347&view=logs&j=93d3aa94-bfaf-5ccd-d833-13f8ece03570&t=fed74b13-efc0-5d8c-a5f7-1062d3f552aa).

The second one is also not directly from our code (and does not show up on the azure pipeline tests), but must come from some imported dependency (not sure which one).
