### ISSUE TITLE
PowderDiffraction works only for isotropic convolvers

### ISSUE THREAD

**Issue by dkriegner** [dkriegner/xrayutilities#35]
If a powder profile depends on the Miller indices HKL the powder diffraction class needs to treat all contributions to a powder line independently. This is not done by default since it would significantly slow down the calculation but should optionally be possible to allow for such anisotropic convolvers (e.g. anisotropic size of crystallites)

**Comment by mendenmh** [comment]
If this is specifically used for cases in which there are same-angle peaks corresponding to non-equivalent hkls, then it makes sense.  I've not dealt with this case in the past, although it can happen.  One still (in the actual implementation) want to make sure that fully symmetry-equivalent hkls  are not recomputed, since the number of equivalent cases is often quite high.

On Jan 31, 2017, at 10:17 AM, Dominik Kriegner <notifications@github.com<mailto:notifications@github.com>> wrote:


The mentioned commit should technically fix this issue but I want to get confirmation from @mendenmh<https://github.com/mendenmh> if its also done reasonable clever.

I have added a class attribute in the FP_profile class named 'isotropic' which is True in the currently built in version. If one uses anisotropic convolvers I propose to derive a subclass like this

class aniFP_prof(xrayutilities.simpack.FP_profile):
    isotropic = False
    ...


to mark it as anisotropic. In such cases every HKL is treated independently which of course significantly slows down the calculation but I guess is not avoidable (except that isotropic contributions at the same 2Theta could in principle be shared by the different contributions, but this seems complicated and would in my opinion require some redesigning of FP_profile). I am eager to hear other opinions!

**Comment by dkriegner** [comment]
Currently this does not consider any symmetry equivalent peaks. Personally I think that multiple levels of anisotropy are possible:

1) no anisotropy as it is with isotropic=True, which means all peaks at the same angle independent of their hkl can be combined
2) full anisotropy (which is now isotropic=False) as it would be induced by an anisotropic crystal shape which is linked to a crystal direction. for example rod shaped crystallites would even make symmetry equivalent contributions to one line broadened in a different way. Can this be handled somehow analytical without treating every peak independent?
3) an intermediate case were the crystal symmetry is preserved and symmetry equivalent peaks can be combined. I guess this can be implemented without big hazzle. modifications will be limited to the [PowderDiffraction.merge_lines method](https://github.com/dkriegner/xrayutilities/blob/master/xrayutilities/simpack/powder.py#L2003)

Are all three cases relevant or only 1 and 3 as suggested by your previous comment?

**Comment by mendenmh** [comment]
Case two, although it is easy to implement, would be computationally terrible, since all the degenerate peaks would be presumably computed separately.  In high-symmetry materials, the degeneracy can be 12, or 24 even!  The code that knows about the symmetry should be able to generate a sample hkl corresponding to one peak in each symmetry class, and then a degeneracy factor which is just a simple multiplier on intensity.

On Jan 31, 2017, at 3:05 PM, Dominik Kriegner <notifications@github.com<mailto:notifications@github.com>> wrote:


Currently this does not consider any symmetry equivalent peaks. Personally I think that multiple levels of anisotropy are possible:

  1.  no anisotropy as it is with isotropic=True, which means all peaks at the same angle independent of their hkl can be combined
  2.  full anisotropy (which is now isotropic=False) as it would be induced by an anisotropic crystal shape which is linked to a crystal direction. for example rod shaped crystallites would even make symmetry equivalent contributions to one line broadened in a different way. Can this be handled somehow analytical without treating every peak independent?
  3.  an intermediate case were the crystal symmetry is preserved and symmetry equivalent peaks can be combined. I guess this can be implemented without big hazzle. modifications will be limited to the PowderDiffraction.merge_lines method<https://github.com/dkriegner/xrayutilities/blob/master/xrayutilities/simpack/powder.py#L2003>

Are all three cases relevant or only 1 and 3 as suggested by your previous comment?

**Comment by dkriegner** [comment]
I will implement case 3 since I only need the knowledge about the crystal symmetry which is included in my part of the code.

Case 2: To improve the performance depending on the model there will be some "user input" needed. I could imagine that the FP_profile subclass which implements a specific anisotropic model needs to supply a function which reduces the list of all HKL indices to the necessary minimum needed to allow for its correct simulation. I need to think of an appropriate interface for this. but If such models do not exist currently we could also leave this open and decide later.

**Comment by dkriegner** [comment]
I have now added code which should fix this issue for the moment.

Case 1 (fully isotropic (default) and case 3 (minimal anisotropy, e.g. in a cubic system 511 and 333 are different, but all {333} are grouped together) is now implemented.
If a convolver model requires a higher degree of anisotropy it needs to supply a function which determines which hkl (at the same 2Theta angle) are equal. This function is called when 
FP_class.isotropic = False and an example which would yield to full anisotropy is shown below:

```
import xrayutilities
class fp(xrayutilities.simpack.FP_profile):
    isotropic = False

    @classmethod
    def isequivalent(cls, hkl1, hkl2, crystalsystem):
        return False
```
