### ISSUE TITLE
[Bug] Packaging for debian

### ISSUE THREAD

**Issue by alexmarie78** [dkriegner/xrayutilities#68]
Hello,
I am trying to package python-xrayutilities for debian.
While running the test, some are skipped because with python version lower than 3.3, the package requires lzma module. 
I added it in the debian/control file in the recommend part, but could it be possible to have it in the optional dep in setup.py file ?
Cheers,
Alex

**Comment by dkriegner** [comment]
yes, adding the lzma module there would be possible... 
Would this diff look ok for this purpose:

```
@@ -157,6 +157,7 @@ setup(
     extras_require={
         'plot': ["matplotlib"],
         'fit': ["lmfit"],
+        'lzma': ["lzma"],
         },
     include_dirs=[numpy.get_include()],
     ext_modules=[extmodul],
```

This of course still does not make the tests being run on python2.7 but I consider that uncritical since the skipped tests are only for routines testing the creation of the element database which is shipped pre-built in all downloads (including the GIT repo)
Adding the LZMA module as optional dependency still makes sense because also in the code there are some options which would use it (see e.g. https://github.com/dkriegner/xrayutilities/blob/master/xrayutilities/io/helper.py#L77).

btw: I hope you are aware of the existing effort to bring the package to debian
https://salsa.debian.org/science-team/python-xrayutilities
In the end there where some licensing concerns. @eugenwintersberger know all the details.

**Comment by alexmarie78** [comment]
This look fine to me.
Yes I am aware of the existing effort but I want to bring the 1.5.1 version to debian as the actual one is 1.2.0.
Thanks for your response

**Comment by farhi** [comment]
We at Synchrotron Soleil have finalized the packaging of xrayutilities for Debian (version 1.6). The package has been pushed to Debian SID "unstable" and now "testing". The work has been subcontracted to the Freexian company, specialized in packaging.

You can follow the common effort here:
- https://tracker.debian.org/pkg/xrayutilities

were you will find source and binary (amd64) packages. They will appear in all future Debian-derivatives.

It should later appear in Debian 'SID' unstable with attached source and binary (e.g. amd64) package files.

**Comment by dkriegner** [comment]
thanks for the information.

I will look into patches which potentially can be upstreamed (see e.g. #109, feel free to report issues when patches seem to be generally helpful and not very Debian specific).
