### ISSUE TITLE
spec IO

### ISSUE THREAD

**Issue by dschick** [dkriegner/xrayutilities#71]
Hej,

I have currently some issues reading SPEC files (which are actually created by the Sardana project) that do include `nan `and `inf` in the data columns as well as empty scans (so just a scan header without data coulumns).
In these cases the whole file does not seem to be read correctly and stored to hdf5.

Best

Daniel

**Comment by dkriegner** [comment]
Thank for the report, please attach one of the problematic files to the report to allow for testing. Empty scans should in principle work. Nan and inf might not be parsed correctly at the moment. Should be easy to fix

If the files are too large Just strip them down to few relevant scans

**Comment by dkriegner** [comment]
it might be possible that the mentioned commit fixes the issue with nan/inf. 
I am not entirely happy with this solution since it relies on me defining a overly complicated regular expression. I should investigate if this can not be avoided in this case which further could speed up the code.

please confirm that your issue is still existing with the GIT master code and in particular be more specific about the misbehavior for empty scans. in principle empty scans should be treated correctly but there are always surprises with SPEC files and your empty scans might need a special condition in my code

**Comment by dkriegner** [comment]
without major changes to this parser I see currently no chance to improve the performance significantly. 

@dschick please check your problem with the current GIT master. inf/nan should now be parsed correctly and I also made changes to treat empty scans correctly. if there are still issues please submit the spec file causing problems or a more detailed error message.

**Comment by dschick** [comment]
hej @dkriegner , it is working like a charm!

Thanks a lot.
