### ISSUE TITLE
setuptools test deprecation

### ISSUE THREAD

**Issue by dkriegner** [dkriegner/xrayutilities#91]
The `setup.py test` command is being [deprecated](https://github.com/pypa/setuptools/commit/cd84510713ada48bf33d4efa749c2952e3fc1a49) and should be replaced by a more universial way to run the tests. Also the tests should be able to run before installation of the code. This means the imported xrayutilities version should not be the systems one but the one built by setup.py.

All this should be achievable by [tox](https://tox.readthedocs.io/en/latest/)
also note the respective [travis ci support](https://github.com/tox-dev/tox-travis).

**Comment by alexmarie78** [comment]
Hello again, 
Here is the problem I get when I don't copy the egg-info in the buildpackage dir during the packaging process.
The egg-info are not generated in the build directory.

so in order to make it work, we need to copy the egg info into the build directory with this command

```
{interpreter} {dir}/setup.py egg_info -e {build_dir};
```

Usually other python packages used a trick in the setup.py file, via a dedicated VERSION file, in order to obtain the version of the package.

Just to let you know about one of our difficulties.

======================================================================
ERROR: tests.test_simpack_dynamicalmodel (unittest2.loader._FailedTest)
----------------------------------------------------------------------
Traceback (most recent call last):
ImportError: Failed to import test module: tests.test_simpack_dynamicalmodel
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/unittest2/loader.py", line 456, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/lib/python3/dist-packages/unittest2/loader.py", line 395, in _get_module_from_name
    __import__(name)
  File "/<<PKGBUILDDIR>>/.pybuild/cpython3_3.7_xrayutilities/build/tests/test_simpack_dynamicalmodel.py", line 22, in <module>
    import xrayutilities as xu
  File "/<<PKGBUILDDIR>>/.pybuild/cpython3_3.7_xrayutilities/build/xrayutilities/__init__.py", line 45, in <module>
    __version__ = pkg_resources.get_distribution("xrayutilities").version
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 481, in get_distribution
    dist = get_provider(dist)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 357, in get_provider
    return working_set.find(moduleOrReq) or require(str(moduleOrReq))[0]
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'xrayutilities' distribution was not found and is required by the application

**Comment by alexmarie78** [comment]
Hello,

In order to make it easy to test xrayutilities, it would be nice to have something equivalent to the numpy test.

The Idea is to be able to run the untitest on your computer, with a simple

xrayutilities.tests()

then producing integration tests is as simple as

python -m xrayutilities.tests

**Comment by dkriegner** [comment]
Let me answer point by point, but keep in mind that most of the work on this project is done in my spare time. So do no expect miracles. Patches are always welcome!

> Usually other python packages used a trick in the setup.py file, via a dedicated VERSION file, in order to obtain the version of the package.

You refer to a solution similar to point 4 in https://packaging.python.org/guides/single-sourcing-package-version/ ? the problem with a dedicated version file is that it would need to be placed in the package sources. the solution to have the version file in the root folder seems more logical. I understand this causes pain for you during the package testing. I will think about it.

> In order to make it easy to test xrayutilities, it would be nice to have something equivalent to the numpy test.
> 
> The Idea is to be able to run the untitest on your computer, with a simple
> 
> xrayutilities.tests()

If you see my recent commits to master you will see that i refactored the things a bit to work with tox. This is not finished but from my perspective the most universal thing i can do since the respective configs are reused on Travis-CI and app-veyor to test different platforms and I can also use it to measure the code coverage directly during the integration testing.

I understand that there might be more convenient things for you as a downstream packager but from my point of few reusing existing efforts to make things easier for me (like tox) seems to be the best thing I can do.

> In order to avoid issues in tests, I had to to this on the setup.py file :
> 
> ```
> -            build = self.get_finalized_command('build')
> -            sys.path.insert(0, os.path.abspath(build.build_lib))
> +            # build = self.get_finalized_command('build')
> +            # sys.path.insert(0, os.path.abspath(build.build_lib))
> ```
> 
> What do you think about that?

I do not understand how this effects the tests. This code should only be executed when you build the documentation? (your diff further seems broken because you should also take away the sys.path.pop line below.
Generally this code (all the build_doc part) somehow via Eugen comes from your boss I think. Generally I would not need this modification because for my use I can build the documentation from the installed package. So this code was included to make the debian packaging more easy!
This being said: from my point of view all of build_doc can be removed and just be filled with the standard setuptools version but i thought this is problematic for you?

**Comment by dkriegner** [comment]
> > Usually other python packages used a trick in the setup.py file, via a dedicated VERSION file, in order to obtain the version of the package.
> 
> You refer to a solution similar to point 4 in https://packaging.python.org/guides/single-sourcing-package-version/ ? the problem with a dedicated version file is that it would need to be placed in the package sources. the solution to have the version file in the root folder seems more logical. I understand this causes pain for you during the package testing. I will think about it.

Since we already used a dedicated VERSION file I just moved it into the package sources and use this instead of `pkg_resources`. This issue should therefore be fixed. Let me however point out that I found my original version more elegant in general since the VERSION file resided in the package root where it in my opinion belongs. I do however not understand how to install it into the python package from this location in a way that i can find them again in the python package.` setup.py data_files` does not work for me since I found that when using` setup.py install `or `pip install . `these data files actually end up in different locations. If you know how that works consistently i would appreciate a hint! 

Also your problems during the testing somehow show that one should install the package fully into some virtual environment where it really runs like in a user environment and not only perform partial builds with setuptools. I understand this is not your fault (nor mine) but somehow a limitation of python packaging. thats why I think the testing I now do on travis and appveyor using tox should give the most consistent results
